---
- name: learning error handling
  hosts: planet-express

  tasks:

  ###### PRECHECK PHASE ###### 
  - name: PRECHECK
    block:
    - debug:
        msg: "I am a precheck step"

    - debug:
        msg: "I am another precheck step"

    #    - command: "/bin/false" # this always returns a false, which forces a fail

    rescue:
    - fail:
        msg: "The precheck phase has FAILED. Exiting"

  ####### MAINTENANCE PHASE ########
  - name: MAINTENANCE PHASE 
    block:
    - debug:
        msg: "I am a step that makes a change"

    - debug:
        msg: "I am another step that makes a change"

    #- command: "/bin/false"

    rescue:
    - debug:
        msg: "The maintence phase has FAILED. ROLLING BACK!"

    - debug:
        msg: "I am a step that undoes the first step in the maintenance block"

    - fail:
        msg: "The maintenance phase has been ROLLED BACK. EXITING!"

  ######## POST CHECK PHASE ########
  - name: POST CHECK PHASE
    block:
    - debug:
        msg: "I am a step that checks if changes were successful"

    #- command: "/bin/false"

    rescue:
    - debug:
        msg: "The post-check  phase has FAILED. ROLLING BACK!"

    - debug:
        msg: "I am a step that undoes the first step in the maintenance block"

    - fail:
        msg: "The post-check phase has been ROLLED BACK. EXITING!"
